name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install requests

      - name: Update geo data
        run: python3 update.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ip_to_geo.json
          commit_message: Update geo data
