name: Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: sudo apt-get install -y geoip-bin

      - name: Update
        run: python scripts/update_serverinfo.py

      # commit
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ip_to_geo.json
